#!/usr/bin/env sh

dotnet publish Taskington.App/Taskington.App.csproj --configuration Release -r osx-arm64 --self-contained true -p:PublishTrimmed=true -p:UseAppHost=true -p:CIBuild=true --output ./output/publish-macosarm64
