#!/usr/bin/env sh

ASSEMBLYVERSION=`buildtools/versionize --next`
FULLASSEMBLYVERSION=`buildtools/versionize --assembly`
INFOVERSION=`buildtools/versionize`

dotnet publish Taskington.Gui/Taskington.Gui.csproj --configuration Release -r osx-arm64 --self-contained true -p:PublishTrimmed=true -p:UseAppHost=true -p:Version=$ASSEMBLYVERSION -p:FileVersion=$FULLASSEMBLYVERSION -p:InformationalVersion=$INFOVERSION -p:CIBuild=true --output ./output/publish-macosarm64
