#!/usr/bin/env sh

dotnet publish Taskington.Gui/Taskington.Gui.csproj --configuration Release -r win-x64 --self-contained true -p:PublishTrimmed=true -p:UseAppHost=true --output ./output/publish-win64
